export interface Country {
  code: string;
  name: string;
  nameFr: string;
  currency: string;
  phonePrefix: string;
  timezone: string;
  regions: string[];
  cities: string[];
}

export const countries: Country[] = [
  { code: 'CM', name: 'Cameroon', nameFr: 'Cameroun', currency: 'XAF', phonePrefix: '+237', timezone: 'Africa/Douala',
    regions: ['Centre','Littoral','Ouest','Sud-Ouest','Nord-Ouest','Sud','Est','Adamaoua','North','Far North','Extrême-Nord'],
    cities: ['Douala','Yaoundé','Bamenda','Bafoussam','Garoua','Maroua','Buea','Limbe','Kribi','Ebolowa'] },
  { code: 'SN', name: 'Senegal', nameFr: 'Sénégal', currency: 'XOF', phonePrefix: '+221', timezone: 'Africa/Dakar',
    regions: ['Dakar','Thiès','Saint-Louis','Diourbel','Fatick','Tambacounda','Kaolack','Kolda','Ziguinchor','Matam','Louga','Sédhiou','Kaffrine'],
    cities: ['Dakar','Thiès','Saint-Louis','Touba','Kaolack','Ziguinchor','Rufisque','Mbour','Diourbel','Louga'] },
  { code: 'CI', name: "Côte d'Ivoire", nameFr: "Côte d'Ivoire", currency: 'XOF', phonePrefix: '+225', timezone: 'Africa/Abidjan',
    regions: ['Abidjan','Bas-Sassandra','Comoé','Denguélé','Gôh-Djiboua','Lacs','Lagunes','Montagnes','Sassandra-Marahoué','Savanes','Woroba','Yamoussoukro','Zanzan'],
    cities: ['Abidjan','Bouaké','Yamoussoukro','Daloa','San-Pédro','Korhogo','Man','Divo','Gagnoa','Séguéla'] },
  { code: 'NG', name: 'Nigeria', nameFr: 'Nigeria', currency: 'NGN', phonePrefix: '+234', timezone: 'Africa/Lagos',
    regions: ['Lagos','Abuja FCT','Rivers','Kano','Oyo','Kaduna','Enugu','Delta','Anambra','Edo','Imo','Cross River','Ogun','Ondo','Osun','Benue','Plateau'],
    cities: ['Lagos','Abuja','Kano','Ibadan','Port Harcourt','Benin City','Kaduna','Enugu','Aba','Jos','Ilorin','Owerri'] },
  { code: 'KE', name: 'Kenya', nameFr: 'Kenya', currency: 'KES', phonePrefix: '+254', timezone: 'Africa/Nairobi',
    regions: ['Nairobi','Mombasa','Kisumu','Nakuru','Eldoret','Kiambu','Machakos','Nyeri','Meru','Kakamega','Bungoma','Garissa','Kilifi','Kisii'],
    cities: ['Nairobi','Mombasa','Kisumu','Nakuru','Eldoret','Ruiru','Kikuyu','Thika','Naivasha','Nyeri'] },
  { code: 'GH', name: 'Ghana', nameFr: 'Ghana', currency: 'GHS', phonePrefix: '+233', timezone: 'Africa/Accra',
    regions: ['Greater Accra','Ashanti','Western','Central','Eastern','Northern','Volta','Upper East','Upper West','Bono','Bono East','Ahafo','Oti','Western North','Savannah','North East'],
    cities: ['Accra','Kumasi','Tamale','Takoradi','Cape Coast','Tema','Sekondi','Sunyani','Koforidua','Wa'] },
  { code: 'ZA', name: 'South Africa', nameFr: 'Afrique du Sud', currency: 'ZAR', phonePrefix: '+27', timezone: 'Africa/Johannesburg',
    regions: ['Gauteng','Western Cape','KwaZulu-Natal','Eastern Cape','Free State','Limpopo','Mpumalanga','North West','Northern Cape'],
    cities: ['Johannesburg','Cape Town','Durban','Pretoria','Port Elizabeth','Bloemfontein','East London','Pietermaritzburg','Polokwane','Nelspruit'] },
  { code: 'EG', name: 'Egypt', nameFr: 'Égypte', currency: 'EGP', phonePrefix: '+20', timezone: 'Africa/Cairo',
    regions: ['Cairo','Alexandria','Giza','Aswan','Asyut','Beheira','Dakahlia','Damietta','Faiyum','Gharbia','Ismailia','Kafr el-Sheikh','Luxor','Minya','Monufia','New Valley','North Sinai','Port Said','Qalyubia','Qena','Red Sea','Sharqia','Sohag','South Sinai','Suez'],
    cities: ['Cairo','Alexandria','Giza','Luxor','Aswan','Port Said','Suez','Mansoura','Tanta','Asyut'] },
  { code: 'MA', name: 'Morocco', nameFr: 'Maroc', currency: 'MAD', phonePrefix: '+212', timezone: 'Africa/Casablanca',
    regions: ['Casablanca-Settat','Rabat-Salé-Kénitra','Fès-Meknès','Marrakech-Safi','Tanger-Tétouan-Al Hoceïma','Souss-Massa','Oriental','Béni Mellal-Khénifra','Drâa-Tafilalet','Guelmim-Oued Noun','Laâyoune-Sakia El Hamra','Dakhla-Oued Ed-Dahab'],
    cities: ['Casablanca','Rabat','Marrakech','Fès','Tanger','Agadir','Meknès','Oujda','Kénitra','Tétouan'] },
  { code: 'DZ', name: 'Algeria', nameFr: 'Algérie', currency: 'DZD', phonePrefix: '+213', timezone: 'Africa/Algiers',
    regions: ['Alger','Oran','Constantine','Annaba','Blida','Batna','Sétif','Tlemcen','Béjaïa','Tizi Ouzou','Skikda','Biskra','Mostaganem'],
    cities: ['Alger','Oran','Constantine','Annaba','Blida','Batna','Sétif','Tlemcen','Béjaïa','Tizi Ouzou'] },
  { code: 'ET', name: 'Ethiopia', nameFr: 'Éthiopie', currency: 'ETB', phonePrefix: '+251', timezone: 'Africa/Addis_Ababa',
    regions: ['Addis Ababa','Oromia','Amhara','Tigray','Sidama','Somali','Afar','Benishangul-Gumuz','Gambela','Harari','SNNPR','Diredawa'],
    cities: ['Addis Ababa','Dire Dawa','Adama','Hawassa','Bahir Dar','Mekelle','Jimma','Gondar','Dessie','Shashamane'] },
  { code: 'TZ', name: 'Tanzania', nameFr: 'Tanzanie', currency: 'TZS', phonePrefix: '+255', timezone: 'Africa/Dar_es_Salaam',
    regions: ['Dar es Salaam','Dodoma','Mwanza','Arusha','Mbeya','Morogoro','Tanga','Kilimanjaro','Zanzibar','Tabora','Kigoma','Iringa','Mara','Singida','Rukwa'],
    cities: ['Dar es Salaam','Dodoma','Mwanza','Arusha','Mbeya','Morogoro','Tanga','Zanzibar City','Kigoma','Iringa'] },
  { code: 'UG', name: 'Uganda', nameFr: 'Ouganda', currency: 'UGX', phonePrefix: '+256', timezone: 'Africa/Kampala',
    regions: ['Central','Eastern','Northern','Western','Kampala'],
    cities: ['Kampala','Wakiso','Mukono','Jinja','Entebbe','Gulu','Mbarara','Mbale','Lira','Masaka'] },
  { code: 'BF', name: 'Burkina Faso', nameFr: 'Burkina Faso', currency: 'XOF', phonePrefix: '+226', timezone: 'Africa/Ouagadougou',
    regions: ['Hauts-Bassins','Boucle du Mouhoun','Nord','Centre-Nord','Sahel','Est','Sud-Ouest','Centre','Plateau-Central','Cascade','Centre-Ouest','Centre-Est','Centre-Sud'],
    cities: ['Ouagadougou','Bobo-Dioulasso','Koudougou','Banfora','Ouahigouya','Pô','Tenkodogo','Kaya','Fada N\'gourma','Dédougou'] },
  { code: 'ML', name: 'Mali', nameFr: 'Mali', currency: 'XOF', phonePrefix: '+223', timezone: 'Africa/Bamako',
    regions: ['Bamako','Kayes','Koulikoro','Sikasso','Ségou','Mopti','Tombouctou','Gao','Kidal','Taoudénit','Ménaka'],
    cities: ['Bamako','Sikasso','Ségou','Kayes','Mopti','Niono','Koutiala','Tombouctou','Gao','San'] },
  { code: 'BJ', name: 'Benin', nameFr: 'Bénin', currency: 'XOF', phonePrefix: '+229', timezone: 'Africa/Porto-Novo',
    regions: ['Atlantique','Littoral','Ouémé','Plateau','Zou','Collines','Borgou','Alibori','Atacora','Donga','Mono','Couffo'],
    cities: ['Cotonou','Porto-Novo','Parakou','Abomey-Calavi','Kandi','Natitingou','Lokossa','Ouidah','Bohicon','Dogbo'] },
  { code: 'TG', name: 'Togo', nameFr: 'Togo', currency: 'XOF', phonePrefix: '+228', timezone: 'Africa/Lome',
    regions: ['Maritime','Plateaux','Centrale','Kara','Savanes'],
    cities: ['Lomé','Sokodé','Kara','Atakpamé','Kpalimé','Dapaong','Aného','Tsévié','Blitta','Niamtougou'] },
  { code: 'NE', name: 'Niger', nameFr: 'Niger', currency: 'XOF', phonePrefix: '+227', timezone: 'Africa/Niamey',
    regions: ['Niamey','Agadez','Diffa','Dosso','Maradi','Tahoua','Tillabéri','Zinder'],
    cities: ['Niamey','Zinder','Maradi','Agadez','Tahoua','Diffa','Dosso','Birni-N\'Konni','Tillabéri','Dogondoutchi'] },
  { code: 'GN', name: 'Guinea', nameFr: 'Guinée', currency: 'GNF', phonePrefix: '+224', timezone: 'Africa/Conakry',
    regions: ['Conakry','Nzérékoré','Kankan','Kindia','Boké','Labé','Faranah','Siguiri','Mamou','Koubia','Koundara','Mandiama','Télimélé','Yomou'],
    cities: ['Conakry','Nzérékoré','Kankan','Kindia','Boké','Labé','Mamou','Siguiri','Kamsar','Faranah'] },
  { code: 'RW', name: 'Rwanda', nameFr: 'Rwanda', currency: 'RWF', phonePrefix: '+250', timezone: 'Africa/Kigali',
    regions: ['Kigali','Northern','Southern','Eastern','Western'],
    cities: ['Kigali','Butare','Gitarama','Ruhengeri','Gisenyi','Byumba','Cyangugu','Kibuye','Rwamagana','Kabuga'] },
  { code: 'CD', name: 'DR Congo', nameFr: 'RD Congo', currency: 'CDF', phonePrefix: '+243', timezone: 'Africa/Kinshasa',
    regions: ['Kinshasa','Kongo Central','Kwango','Kwilu','Mai-Ndombe','Kasai','Kasai Central','Kasai Oriental','Lomami','Sankuru','Maniema','South Kivu','North Kivu','Ituri','Haut-Uele','Bas-Uele','Tshopo','Mongala','Nord-Ubangi','Sud-Ubangi','Tshuapa','Équateur','Tanganyika','Haut-Lomami','Lualaba','Haut-Katanga'],
    cities: ['Kinshasa','Lubumbashi','Mbuji-Mayi','Kananga','Kisangani','Goma','Bukavu','Matadi','Kikwit','Likasi'] },
  { code: 'CG', name: 'Congo', nameFr: 'Congo', currency: 'XAF', phonePrefix: '+242', timezone: 'Africa/Brazzaville',
    regions: ['Brazzaville','Kouilou','Pointe-Noire','Cuvette','Cuvette-Ouest','Likouala','Sangha','Plateaux','Pool','Bouenza','Niari','Lékoumou'],
    cities: ['Brazzaville','Pointe-Noire','Dolisie','Nkayi','Impfondo','Owando','Sibiti','Madingou','Mossendjo','Kinkala'] },
  { code: 'GA', name: 'Gabon', nameFr: 'Gabon', currency: 'XAF', phonePrefix: '+241', timezone: 'Africa/Libreville',
    regions: ['Estuaire','Haut-Ogooué','Moyen-Ogooué','Ngounié','Nyanga','Ogooué-Ivindo','Ogooué-Lolo','Ogooué-Maritime','Woleu-Ntem'],
    cities: ['Libreville','Port-Gentil','Franceville','Oyem','Moanda','Mounana','Lambaréné','Tchibanga','Koulamoutou','Makokou'] },
  { code: 'TD', name: 'Chad', nameFr: 'Tchad', currency: 'XAF', phonePrefix: '+235', timezone: 'Africa/Ndjamena',
    regions: ['N\'Djamena','Bahr el Gazel','Batha','Borkou','Ennedi-Est','Ennedi-Ouest','Guéra','Hadjer-Lamis','Kanem','Lac','Logone Occidental','Logone Oriental','Mandoul','Mayo-Kebbi-Est','Moyen-Chari','Ouaddai','Salamat','Sila','Tandjilé','Wadi Fira'],
    cities: ['N\'Djamena','Moundou','Sarh','Abéché','Kelo','Doba','Mongo','Bongor','Faya-Largeau','Ati'] },
  { code: 'CF', name: 'Central African Republic', nameFr: 'République centrafricaine', currency: 'XAF', phonePrefix: '+236', timezone: 'Africa/Bangui',
    regions: ['Bangui','Bamingui-Bangoran','Bangassou','Basse-Kotto','Gribingui','Haut-Mbomou','Haute-Kotto','Haut-Shaba','Kemo-Gribingui','Lobaye','Mambe-Mbaéré','Mbomou','Nana-Mambéré','Ombella-Mpoko','Ouaka','Ouham','Ouham-Pendé','Sangha-Mbaéré','Vakaga'],
    cities: ['Bangui','Bimbo','Carnot','Bambari','Bouar','Bossangoa','Batangafo','Kaga Bandoro','Paoua','Bozoum'] },
  { code: 'AO', name: 'Angola', nameFr: 'Angola', currency: 'AOA', phonePrefix: '+244', timezone: 'Africa/Luanda',
    regions: ['Luanda','Benguela','Huambo','Huíla','Cabinda','Malanje','Namibe','Cuanza Sul','Cuanza Norte','Uíge','Bié','Moxico','Cuando Cubango','Cunene','Bengo','Zaire','Moxico'],
    cities: ['Luanda','Huambo','Benguela','Lobito','Lubango','Kuito','Malanje','Cabinda','Sumbe','Uíge'] },
  { code: 'MZ', name: 'Mozambique', nameFr: 'Mozambique', currency: 'MZN', phonePrefix: '+258', timezone: 'Africa/Maputo',
    regions: ['Maputo City','Maputo','Gaza','Inhambane','Sofala','Manica','Tete','Zambézia','Nampula','Cabo Delgado','Niassa'],
    cities: ['Maputo','Matola','Beira','Nampula','Chimoio','Quelimane','Tete','Lichinga','Pemba','Xai-Xai'] },
  { code: 'ZW', name: 'Zimbabwe', nameFr: 'Zimbabwe', currency: 'USD', phonePrefix: '+263', timezone: 'Africa/Harare',
    regions: ['Bulawayo','Harare','Manicaland','Mashonaland Central','Mashonaland East','Mashonaland West','Masvingo','Matabeleland North','Matabeleland South','Midlands'],
    cities: ['Harare','Bulawayo','Chitungwiza','Mutare','Gweru','Kwekwe','Masvingo','Marondera','Kadoma','Bindura'] },
  { code: 'ZM', name: 'Zambia', nameFr: 'Zambie', currency: 'ZMW', phonePrefix: '+260', timezone: 'Africa/Lusaka',
    regions: ['Lusaka','Copperbelt','Central','Eastern','Luapula','Muchinga','Northern','North-Western','Southern','Western'],
    cities: ['Lusaka','Kitwe','Ndola','Kabwe','Chingola','Livingstone','Mufulira','Luanshya','Kasama','Chipata'] },
  { code: 'MW', name: 'Malawi', nameFr: 'Malawi', currency: 'MWK', phonePrefix: '+265', timezone: 'Africa/Blantyre',
    regions: ['Central','Northern','Southern'],
    cities: ['Lilongwe','Blantyre','Mzuzu','Zomba','Kasungu','Mangochi','Salima','Liwonde','Balaka','Dedza'] },
  { code: 'SL', name: 'Sierra Leone', nameFr: 'Sierra Leone', currency: 'SLL', phonePrefix: '+232', timezone: 'Africa/Freetown',
    regions: ['Western Area','Northern','Southern','Eastern'],
    cities: ['Freetown','Bo','Kenema','Makeni','Koidu','Kabala','Port Loko','Pujehun','Magburaka','Bonthe'] },
  { code: 'LR', name: 'Liberia', nameFr: 'Liberia', currency: 'LRD', phonePrefix: '+231', timezone: 'Africa/Monrovia',
    regions: ['Montserrado','Bomi','Bong','Gbarpolu','Grand Bassa','Grand Cape Mount','Grand Gedeh','Grand Kru','Lofa','Margibi','Maryland','Nimba','River Cess','River Gee','Sinoe'],
    cities: ['Monrovia','Gbarnga','Kakata','Bensonville','Harper','Voinjama','Buchanan','Tubmanburg','Greenville','Zwedru'] },
  { code: 'GM', name: 'Gambia', nameFr: 'Gambie', currency: 'GMD', phonePrefix: '+220', timezone: 'Africa/Banjul',
    regions: ['Banjul','Brikama','Mansa Konko','Kerewan','Kuntaur','Janjanbureh','Basse'],
    cities: ['Banjul','Serekunda','Brikama','Bakau','Farafenni','Basse Santa Su','Janjanbureh','Brufut','Kololi','Gunjur'] },
  { code: 'MR', name: 'Mauritania', nameFr: 'Mauritanie', currency: 'MRU', phonePrefix: '+222', timezone: 'Africa/Nouakchott',
    regions: ['Nouakchott','Adrar','Assaba','Brakna','Dakhlet Nouadhibou','Gorgol','Guidimaka','Hodh Ech Chargui','Hodh El Gharbi','Inchiri','Tagant','Tiris Zemmour','Trarza'],
    cities: ['Nouakchott','Nouadhibou','Néma','Kaédi','Rosso','Zouérat','Atar','Sélibaby','Aleg','Tidjikja'] },
  { code: 'LY', name: 'Libya', nameFr: 'Libye', currency: 'LYD', phonePrefix: '+218', timezone: 'Africa/Tripoli',
    regions: ['Tripoli','Benghazi','Misrata','Zawiya','Zliten','Jabal al Gharbi','Murqub','Wahat','Nalut','Derna','Tobruk','Sabha','Ghat','Wadi al Hayaa','Marj','Sirte','Jufra','Kufra'],
    cities: ['Tripoli','Benghazi','Misrata','Zawiya','Zliten','Sirte','Sabha','Tobruk','Derna','Ajdabiya'] },
  { code: 'TN', name: 'Tunisia', nameFr: 'Tunisie', currency: 'TND', phonePrefix: '+216', timezone: 'Africa/Tunis',
    regions: ['Tunis','Ariana','Ben Arous','Manouba','Nabeul','Zaghouan','Bizerte','Béja','Jendouba','Kef','Siliana','Sousse','Monastir','Mahdia','Sfax','Kairouan','Kasserine','Sidi Bouzid','Gabès','Medenine','Tataouine','Gafsa','Tozeur','Kebili'],
    cities: ['Tunis','Sfax','Sousse','Kairouan','Bizerte','Gabès','Ariana','Gafsa','Monastir','Ben Arous'] },
  { code: 'SD', name: 'Sudan', nameFr: 'Soudan', currency: 'SDG', phonePrefix: '+249', timezone: 'Africa/Khartoum',
    regions: ['Khartoum','Red Sea','River Nile','Northern','Kassala','North Darfur','South Darfur','West Darfur','Central Darfur','East Darfur','North Kordofan','South Kordofan','West Kordofan','Al Qadarif','Sennar','Blue Nile','White Nile'],
    cities: ['Khartoum','Omdurman','Nyala','Port Sudan','Kassala','Al Qadarif','Wad Madani','El Obeid','Dongola','Kusti'] },
  { code: 'SS', name: 'South Sudan', nameFr: 'Soudan du Sud', currency: 'SSP', phonePrefix: '+211', timezone: 'Africa/Juba',
    regions: ['Central Equatoria','Eastern Equatoria','Western Equatoria','Jonglei','Lakes','Warrap','Western Bahr el Ghazal','Northern Bahr el Ghazal','Unity','Upper Nile'],
    cities: ['Juba','Wau','Malakal','Yei','Bor','Rumbek','Aweil','Yambio','Bentiu','Torit'] },
  { code: 'SO', name: 'Somalia', nameFr: 'Somalie', currency: 'SOS', phonePrefix: '+252', timezone: 'Africa/Mogadishu',
    regions: ['Banaadir','Bakool','Bari','Bay','Galguduud','Gedo','Hiran','Lower Juba','Middle Juba','Mudug','Nugal','Sanaag','Lower Shabelle','Middle Shabelle','Togdheer','Awdal','Sool','Nugal'],
    cities: ['Mogadishu','Hargeisa','Bosaso','Kismayo','Baidoa','Garowe','Burao','Merca','Berbera','Jowhar'] },
  { code: 'DJ', name: 'Djibouti', nameFr: 'Djibouti', currency: 'DJF', phonePrefix: '+253', timezone: 'Africa/Djibouti',
    regions: ['Djibouti','Arta','Ali Sabieh','Dikhil','Tadjourah','Obock'],
    cities: ['Djibouti City','Ali Sabieh','Dikhil','Tadjoura','Obock','Arta','Doralé','Yoboki','Randa','Loyada'] },
  { code: 'ER', name: 'Eritrea', nameFr: 'Érythrée', currency: 'ERN', phonePrefix: '+291', timezone: 'Africa/Asmara',
    regions: ['Anseba','Debub','Gash-Barka','Maekel','Northern Red Sea','Southern Red Sea'],
    cities: ['Asmara','Keren','Massawa','Assab','Mendefera','Barentu','Adi Keyh','Decamhare','Ghinda','Teseney'] },
  { code: 'KM', name: 'Comoros', nameFr: 'Comores', currency: 'KMF', phonePrefix: '+269', timezone: 'Indian/Comoro',
    regions: ['Grande Comore','Anjouan','Mohéli'],
    cities: ['Moroni','Mutsamudu','Fomboni','Domoni','Tsimbeo','Ouzou','Moya','Mbeni','Bazimini','Iconi'] },
  { code: 'CV', name: 'Cape Verde', nameFr: 'Cap-Vert', currency: 'CVE', phonePrefix: '+238', timezone: 'Atlantic/Cape_Verde',
    regions: ['Santiago','São Vicente','Santo Antão','Fogo','Brava','Sal','Boa Vista','Maio','São Nicolau'],
    cities: ['Praia','Mindelo','Espargos','Assomada','Porto Novo','Santa Maria','São Filipe','Ribeira Grande','Vila do Maio','Tarrafal'] },
  { code: 'ST', name: 'São Tomé and Príncipe', nameFr: 'São Tomé-et-Príncipe', currency: 'STN', phonePrefix: '+239', timezone: 'Africa/Sao_Tome',
    regions: ['São Tomé','Príncipe','Água Grande','Cantagalo','Caué','Lembá','Lobata','Mé-Zóchi'],
    cities: ['São Tomé','Santo António','Neves','Trindade','Guadalupe','Santana','Angolares','Santa Catarina','Ribeira Afonso','Pangaim'] },
  { code: 'GY', name: 'Guinea-Bissau', nameFr: 'Guinée-Bissau', currency: 'XOF', phonePrefix: '+245', timezone: 'Africa/Bissau',
    regions: ['Bissau','Biombo','Bolama','Cacheu','Gabu','Oio','Quinara','Tombali','Bafatá'],
    cities: ['Bissau','Bafatá','Gabú','Bissorã','Bolama','Cacheu','Catió','Farim','Quinhámel','Mansôa'] },
  { code: 'EH', name: 'Western Sahara', nameFr: 'Sahara occidental', currency: 'MAD', phonePrefix: '+212', timezone: 'Africa/El_Aaiun',
    regions: ['Es Semara','Laâyoune','Boujdour','Oued Ed-Dahab','Aousserd'],
    cities: ['El Aaiún','Dakhla','Smara','Cape Bojador','Lagouira','Bir Lehlou','Tichla','Guelta Zemmur','Mijek','Auserd'] },
  { code: 'BW', name: 'Botswana', nameFr: 'Botswana', currency: 'BWP', phonePrefix: '+267', timezone: 'Africa/Gaborone',
    regions: ['Central','Ghanzi','Kgalagadi','Kgatleng','Kweneng','North West','North-East','South East','Southern'],
    cities: ['Gaborone','Francistown','Molepolole','Serowe','Selebi-Phikwe','Maun','Mahalapye','Mochudi','Kanye','Mogoditshane'] },
  { code: 'NA', name: 'Namibia', nameFr: 'Namibie', currency: 'NAD', phonePrefix: '+264', timezone: 'Africa/Windhoek',
    regions: ['Erongo','Hardap','Kavango East','Kavango West','Karas','Khomas','Kunene','Ohangwena','Omaheke','Omusati','Oshana','Oshikoto','Otjozondjupa','Zambezi'],
    cities: ['Windhoek','Rundu','Walvis Bay','Swakopmund','Oshakati','Rehoboth','Keetmanshoop','Ondangwa','Okahandja','Gobabis'] },
  { code: 'LS', name: 'Lesotho', nameFr: 'Lesotho', currency: 'LSL', phonePrefix: '+266', timezone: 'Africa/Maseru',
    regions: ['Berea','Butha-Buthe','Leribe','Mafeteng','Maseru','Mohale\'s Hoek','Mokhotlong','Qacha\'s Nek','Quthing','Thaba-Tseka'],
    cities: ['Maseru','Teyateyaneng','Maputsoe','Mafeteng','Mohale\'s Hoek','Qacha\'s Nek','Butha-Buthe','Hlotse','Mokhotlong','Quthing'] },
  { code: 'SZ', name: 'Eswatini', nameFr: 'Eswatini', currency: 'SZL', phonePrefix: '+268', timezone: 'Africa/Mbabane',
    regions: ['Hhohho','Lubombo','Manzini','Shiselweni'],
    cities: ['Mbabane','Manzini','Big Bend','Mhlume','Piggs Peak','Siteki','Nhlangano','Lobamba','Malkerns','Tshaneni'] },
  { code: 'MU', name: 'Mauritius', nameFr: 'Maurice', currency: 'MUR', phonePrefix: '+230', timezone: 'Indian/Mauritius',
    regions: ['Port Louis','Pamplemousses','Rivière du Rempart','Flacq','Grand Port','Savanne','Plaines Wilhems','Moka','Black River','Rodrigues'],
    cities: ['Port Louis','Curepipe','Vacoas','Quatre Bornes','Rose Hill','Beau Bassin','Calebasses','Goodlands','Mahébourg','Triolet'] },
  { code: 'SC', name: 'Seychelles', nameFr: 'Seychelles', currency: 'SCR', phonePrefix: '+248', timezone: 'Indian/Mahe',
    regions: ['Anse aux Pins','Anse Boileau','Anse Etoile','Anse Royale','Au Cap','Baie Lazare','Beau Vallon','Bel Omb','Bel Air','Cascade','Glacis','Grand Anse Mahé','Grand Anse Praslin','Inner Islands','Les Mamelles','Mont Buxton','Mont Fleuri','Plaisance','Pointe La Rue','Roche Caiman','Saint Louis','Takamaka','Outer Islands'],
    cities: ['Victoria','Anse Royale','Beau Vallon','Cascade','Takamaka','Anse Boileau','Baie Lazare','Au Cap','Glacis','Pralin'] },

  // International — Klasoo is a genuinely global, multi-tenant platform, not limited to Africa.
  { code: 'FR', name: 'France', nameFr: 'France', currency: 'EUR', phonePrefix: '+33', timezone: 'Europe/Paris',
    regions: ['Île-de-France','Auvergne-Rhône-Alpes','Nouvelle-Aquitaine','Occitanie','Hauts-de-France','Grand Est','Provence-Alpes-Côte d\'Azur'],
    cities: ['Paris','Marseille','Lyon','Toulouse','Nice','Nantes','Strasbourg','Montpellier','Bordeaux','Lille'] },
  { code: 'BE', name: 'Belgium', nameFr: 'Belgique', currency: 'EUR', phonePrefix: '+32', timezone: 'Europe/Brussels',
    regions: ['Bruxelles-Capitale','Flandre','Wallonie'], cities: ['Bruxelles','Anvers','Gand','Charleroi','Liège','Namur'] },
  { code: 'CH', name: 'Switzerland', nameFr: 'Suisse', currency: 'CHF', phonePrefix: '+41', timezone: 'Europe/Zurich',
    regions: ['Zurich','Genève','Vaud','Berne'], cities: ['Zurich','Genève','Lausanne','Berne','Bâle'] },
  { code: 'GB', name: 'United Kingdom', nameFr: 'Royaume-Uni', currency: 'GBP', phonePrefix: '+44', timezone: 'Europe/London',
    regions: ['Angleterre','Écosse','Pays de Galles','Irlande du Nord'], cities: ['Londres','Manchester','Birmingham','Glasgow','Liverpool'] },
  { code: 'DE', name: 'Germany', nameFr: 'Allemagne', currency: 'EUR', phonePrefix: '+49', timezone: 'Europe/Berlin',
    regions: ['Bavière','Berlin','Hesse','Rhénanie-du-Nord-Westphalie'], cities: ['Berlin','Munich','Hambourg','Francfort','Cologne'] },
  { code: 'ES', name: 'Spain', nameFr: 'Espagne', currency: 'EUR', phonePrefix: '+34', timezone: 'Europe/Madrid',
    regions: ['Madrid','Catalogne','Andalousie'], cities: ['Madrid','Barcelone','Valence','Séville'] },
  { code: 'PT', name: 'Portugal', nameFr: 'Portugal', currency: 'EUR', phonePrefix: '+351', timezone: 'Europe/Lisbon',
    regions: ['Lisbonne','Porto','Algarve'], cities: ['Lisbonne','Porto','Braga','Coimbra'] },
  { code: 'IT', name: 'Italy', nameFr: 'Italie', currency: 'EUR', phonePrefix: '+39', timezone: 'Europe/Rome',
    regions: ['Latium','Lombardie','Campanie'], cities: ['Rome','Milan','Naples','Turin'] },
  { code: 'US', name: 'United States', nameFr: 'États-Unis', currency: 'USD', phonePrefix: '+1', timezone: 'America/New_York',
    regions: ['New York','Californie','Texas','Floride'], cities: ['New York','Los Angeles','Chicago','Houston','Miami'] },
  { code: 'CA', name: 'Canada', nameFr: 'Canada', currency: 'CAD', phonePrefix: '+1', timezone: 'America/Toronto',
    regions: ['Québec','Ontario','Colombie-Britannique','Alberta'], cities: ['Toronto','Montréal','Vancouver','Québec','Ottawa'] },
  { code: 'AE', name: 'United Arab Emirates', nameFr: 'Émirats arabes unis', currency: 'AED', phonePrefix: '+971', timezone: 'Asia/Dubai',
    regions: ['Dubaï','Abou Dabi','Charjah'], cities: ['Dubaï','Abou Dabi','Charjah','Ajman'] },
  { code: 'SA', name: 'Saudi Arabia', nameFr: 'Arabie saoudite', currency: 'SAR', phonePrefix: '+966', timezone: 'Asia/Riyadh',
    regions: ['Riyad','La Mecque','Médine'], cities: ['Riyad','Djeddah','La Mecque','Médine'] },
  { code: 'QA', name: 'Qatar', nameFr: 'Qatar', currency: 'QAR', phonePrefix: '+974', timezone: 'Asia/Qatar',
    regions: ['Doha'], cities: ['Doha', 'Al Rayyan', 'Al Wakrah'] },
  { code: 'LB', name: 'Lebanon', nameFr: 'Liban', currency: 'LBP', phonePrefix: '+961', timezone: 'Asia/Beirut',
    regions: ['Beyrouth','Mont-Liban'], cities: ['Beyrouth','Tripoli','Saïda'] },
  { code: 'TR', name: 'Turkey', nameFr: 'Turquie', currency: 'TRY', phonePrefix: '+90', timezone: 'Europe/Istanbul',
    regions: ['Istanbul','Ankara'], cities: ['Istanbul','Ankara','Izmir'] },
  { code: 'IN', name: 'India', nameFr: 'Inde', currency: 'INR', phonePrefix: '+91', timezone: 'Asia/Kolkata',
    regions: ['Delhi','Maharashtra','Karnataka'], cities: ['New Delhi','Mumbai','Bangalore','Chennai'] },
  { code: 'CN', name: 'China', nameFr: 'Chine', currency: 'CNY', phonePrefix: '+86', timezone: 'Asia/Shanghai',
    regions: ['Pékin','Shanghai','Guangdong'], cities: ['Pékin','Shanghai','Canton','Shenzhen'] },
  { code: 'SG', name: 'Singapore', nameFr: 'Singapour', currency: 'SGD', phonePrefix: '+65', timezone: 'Asia/Singapore',
    regions: ['Singapour'], cities: ['Singapour'] },
  { code: 'MY', name: 'Malaysia', nameFr: 'Malaisie', currency: 'MYR', phonePrefix: '+60', timezone: 'Asia/Kuala_Lumpur',
    regions: ['Kuala Lumpur','Selangor'], cities: ['Kuala Lumpur','Johor Bahru','Penang'] },
  { code: 'AU', name: 'Australia', nameFr: 'Australie', currency: 'AUD', phonePrefix: '+61', timezone: 'Australia/Sydney',
    regions: ['Nouvelle-Galles du Sud','Victoria','Queensland'], cities: ['Sydney','Melbourne','Brisbane','Perth'] },
  { code: 'NZ', name: 'New Zealand', nameFr: 'Nouvelle-Zélande', currency: 'NZD', phonePrefix: '+64', timezone: 'Pacific/Auckland',
    regions: ['Auckland','Wellington'], cities: ['Auckland','Wellington','Christchurch'] },
  { code: 'BR', name: 'Brazil', nameFr: 'Brésil', currency: 'BRL', phonePrefix: '+55', timezone: 'America/Sao_Paulo',
    regions: ['São Paulo','Rio de Janeiro'], cities: ['São Paulo','Rio de Janeiro','Brasília'] },
  { code: 'PH', name: 'Philippines', nameFr: 'Philippines', currency: 'PHP', phonePrefix: '+63', timezone: 'Asia/Manila',
    regions: ['Metro Manila'], cities: ['Manille','Cebu','Davao'] },
];

export const currencies: Record<string, { symbol: string; decimals: number; label: string }> = {
  XOF: { symbol: 'FCFA', decimals: 0, label: 'Franc CFA (BCEAO)' },
  XAF: { symbol: 'FCFA', decimals: 0, label: 'Franc CFA (BEAC)' },
  NGN: { symbol: '₦', decimals: 2, label: 'Nigerian Naira' },
  GHS: { symbol: '₵', decimals: 2, label: 'Ghanaian Cedi' },
  KES: { symbol: 'KSh', decimals: 2, label: 'Kenyan Shilling' },
  ZAR: { symbol: 'R', decimals: 2, label: 'South African Rand' },
  EGP: { symbol: 'E£', decimals: 2, label: 'Egyptian Pound' },
  MAD: { symbol: 'DH', decimals: 2, label: 'Moroccan Dirham' },
  DZD: { symbol: 'DA', decimals: 2, label: 'Algerian Dinar' },
  ETB: { symbol: 'Br', decimals: 2, label: 'Ethiopian Birr' },
  TZS: { symbol: 'TSh', decimals: 0, label: 'Tanzanian Shilling' },
  UGX: { symbol: 'USh', decimals: 0, label: 'Ugandan Shilling' },
  USD: { symbol: '$', decimals: 2, label: 'US Dollar' },
  EUR: { symbol: '€', decimals: 2, label: 'Euro' },
  GBP: { symbol: '£', decimals: 2, label: 'British Pound' },
  AED: { symbol: 'AED', decimals: 2, label: 'UAE Dirham' },
  CHF: { symbol: 'CHF', decimals: 2, label: 'Swiss Franc' },
  CAD: { symbol: 'CA$', decimals: 2, label: 'Canadian Dollar' },
  AUD: { symbol: 'A$', decimals: 2, label: 'Australian Dollar' },
  NZD: { symbol: 'NZ$', decimals: 2, label: 'New Zealand Dollar' },
  SAR: { symbol: 'SAR', decimals: 2, label: 'Saudi Riyal' },
  QAR: { symbol: 'QAR', decimals: 2, label: 'Qatari Riyal' },
  LBP: { symbol: 'LBP', decimals: 2, label: 'Lebanese Pound' },
  TRY: { symbol: '₺', decimals: 2, label: 'Turkish Lira' },
  INR: { symbol: '₹', decimals: 2, label: 'Indian Rupee' },
  CNY: { symbol: '¥', decimals: 2, label: 'Chinese Yuan' },
  SGD: { symbol: 'S$', decimals: 2, label: 'Singapore Dollar' },
  MYR: { symbol: 'RM', decimals: 2, label: 'Malaysian Ringgit' },
  BRL: { symbol: 'R$', decimals: 2, label: 'Brazilian Real' },
  PHP: { symbol: '₱', decimals: 2, label: 'Philippine Peso' },
};

export function formatCurrency(amount: number, currency: string): string {
  const cfg = currencies[currency] || currencies.USD;
  const value = amount.toLocaleString('fr-FR', {
    minimumFractionDigits: cfg.decimals,
    maximumFractionDigits: cfg.decimals,
  });
  return `${value} ${cfg.symbol}`;
}

export function getCountry(code: string): Country | undefined {
  return countries.find((c) => c.code === code);
}

// schools.country stores the French display name (set during onboarding), not
// the ISO code — this resolves the right currency for formatCurrency() from that.
export function getCurrencyForCountryName(name: string | null | undefined): string {
  if (!name) return 'USD';
  const match = countries.find((c) => c.nameFr === name || c.name === name);
  return match?.currency || 'USD';
}
