/*
# SKUL AFRIK — Parent-Élève linkage + inscription codes + currency change requests

## New Tables

### parent_eleve
Strict liaison between a parent (auth user) and a student, scoped to a tenant.
- parent_id (auth.users), eleve_id (students), tenant_id (schools)
- type_lien (père/mère/tuteur), statut_verifie (boolean)
- Unique (parent_id, eleve_id, tenant_id)

A parent with no parent_eleve row sees NO student data.

### inscription_codes
Per-student unique code for parent self-joining via /parent/rejoindre.
- eleve_id (unique), tenant_id, code (unique), phone_hint (last 4 digits of registered phone)
- expires_at, used_at (nullable)
- Generated by school at inscription; printed on receipt.

### currency_change_requests
Explicit requests to change currency (locked after onboarding).
- school_id, requested_currency, reason, status (pending/approved/rejected), requested_by, reviewed_by, audit_logged

## RLS
- parent_eleve: parent reads own links; school members read; school_admin writes.
- inscription_codes: school members read; school_admin writes.
- currency_change_requests: school members read; super_admin updates; school_admin inserts.
*/
CREATE TABLE IF NOT EXISTS public.parent_eleve (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  eleve_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  tenant_id uuid NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
  type_lien text NOT NULL DEFAULT 'tuteur' CHECK (type_lien IN ('père','mère','tuteur')),
  statut_verifie boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (parent_id, eleve_id, tenant_id)
);
CREATE INDEX IF NOT EXISTS pe_parent_idx ON public.parent_eleve(parent_id);
CREATE INDEX IF NOT EXISTS pe_eleve_idx ON public.parent_eleve(eleve_id);
CREATE INDEX IF NOT EXISTS pe_tenant_idx ON public.parent_eleve(tenant_id);
ALTER TABLE public.parent_eleve ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "pe_parent_read" ON public.parent_eleve;
CREATE POLICY "pe_parent_read" ON public.parent_eleve FOR SELECT TO authenticated USING (auth.uid() = parent_id OR public.is_school_member(tenant_id));
DROP POLICY IF EXISTS "pe_admin_write" ON public.parent_eleve;
CREATE POLICY "pe_admin_write" ON public.parent_eleve FOR ALL TO authenticated USING (public.is_school_admin(tenant_id)) WITH CHECK (public.is_school_admin(tenant_id));

CREATE TABLE IF NOT EXISTS public.inscription_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  eleve_id uuid NOT NULL UNIQUE REFERENCES public.students(id) ON DELETE CASCADE,
  tenant_id uuid NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
  code text NOT NULL UNIQUE,
  phone_hint text,
  expires_at timestamptz,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ic_tenant_idx ON public.inscription_codes(tenant_id);
CREATE INDEX IF NOT EXISTS ic_code_idx ON public.inscription_codes(code);
ALTER TABLE public.inscription_codes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ic_member_read" ON public.inscription_codes;
CREATE POLICY "ic_member_read" ON public.inscription_codes FOR SELECT TO authenticated USING (public.is_school_member(tenant_id));
DROP POLICY IF EXISTS "ic_admin_write" ON public.inscription_codes;
CREATE POLICY "ic_admin_write" ON public.inscription_codes FOR ALL TO authenticated USING (public.is_school_admin(tenant_id)) WITH CHECK (public.is_school_admin(tenant_id));

CREATE TABLE IF NOT EXISTS public.currency_change_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
  requested_currency text NOT NULL,
  reason text,
  status text NOT NULL DEFAULT 'pending',
  requested_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz
);
ALTER TABLE public.currency_change_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ccr_member_read" ON public.currency_change_requests;
CREATE POLICY "ccr_member_read" ON public.currency_change_requests FOR SELECT TO authenticated USING (public.is_school_member(school_id));
DROP POLICY IF EXISTS "ccr_admin_insert" ON public.currency_change_requests;
CREATE POLICY "ccr_admin_insert" ON public.currency_change_requests FOR INSERT TO authenticated WITH CHECK (public.is_school_admin(school_id));
DROP POLICY IF EXISTS "ccr_super_update" ON public.currency_change_requests;
CREATE POLICY "ccr_super_update" ON public.currency_change_requests FOR UPDATE TO authenticated USING (public.is_super_admin()) WITH CHECK (public.is_super_admin());
